name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy Flake8-pyproject
      - name: Run Flake8
        working-directory: tasks
        run: |
          flake8 --toml-config=../pyproject.toml .
      - name: Run Mypy
        working-directory: tasks
        run: |
          mypy --config-file=../pyproject.toml .
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install --upgrade --editable tools/testlib
      - name: Set up PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      - name: Run Pytest
        working-directory: tasks
        run: |
          pytest
